[package]
name = "datamole"
version = "0.1.0"
edition = "2021"

[features]
std = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "0.2.8"


[dependencies.rand]
version = "0.8.5"
features = ["small_rng"]

